###Mostrar la pagina principal
GET http://localhost:3008/

###Mostrar todas las frutas
GET http://localhost:3008/frutas 


###Mostrar frutas por id
GET http://localhost:3008/frutas/12


###Mostrar frutas por el precio
GET http://localhost:3008/frutas/importe/1000000


###Mostrar frutas por el nombre
GET http://localhost:3008/frutas/nombre/xz

